### ISSUE TITLE
Axios@0.19.2: Critical security vulnerability

### ISSUE THREAD

**Issue by gmahota** [paymentsds/mpesa-js-sdk#56]
Ao correr o build aparece este alerta:

warning @paymentsds/mpesa > axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see 
[https://github.com/axios/axios/pull/3410](https://github.com/axios/axios/pull/3410)

**Comment by thatfiredev** [comment]
Parece-me que foi corrigido em #57

**Comment by gmahota** [comment]
Nice!
